{{- if .Values.persistence.enabled -}}
{{- $fullName := include "vaultwarden.fullname" . -}}
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ $fullName }}
spec:
  {{- with .Values.persistence }}
  capacity:
    storage: {{ .capacity | quote }}
  accessModes:
    - {{ .accessMode | quote }}
  storageClassName: {{ .className | quote }}
  hostPath: 
    path: {{ .volume.path }}
    type: DirectoryOrCreate
  volumeMode: {{ .mode | default "Filesystem" | quote }}
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy | default "Retain" | quote }}
  {{ end }}
{{ end }}
