{{- if .Values.persistence.enabled -}}
{{- $fullName := include "vaultwarden.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ $fullName }}
spec:
  {{- with .Values.persistence }}
  capacity:
    storage: {{ .capacity | quote }}
  accessModes:
    - {{ .accessMode | quote }}
  storageClassName: {{ .className | quote }}
  {{- end -}}
{{- end -}}
