{{- if .Values.persistence.enabled -}}
{{- $fullName := include "vaultwarden.fullname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ $fullName }}
spec:
  {{ with .Values.persistence }}
  storageClassName: {{ .claim.className | quote }}
  {{- if .claim.accessMode }}
  accessModes:
    - {{ .claim.accessMode | quote }}
  resources:
   requests:
     storage: {{ .claim.capacity | quote }}
  {{- end -}}
  {{- end -}}
{{- end -}}
